In [ ]:
THUMB_CMC_ANGLE = 0, 1, 2)
THUMB_MPC_ANGLE = 1,2,3
THUMB_IP_ANGLE = 2,3,4

INDEX_MCP_ANGLE = 0, 5, 6
INDEX_PIP_ANGLE = 5,6,7
INDEX_DIP_ANGLE = 6,7,8

MIDDLE_MPC_ANGLE = 0, 9, 10
MIDDLE_PIP_ANGLE = 9,10,11
MIDDLE_DIP_ANGLE = 10,11,12

RING_MPC_ANGLE = 0, 13, 14
RING_PIP_ANGLE = 13,14,15
RING_DIP_ANGLE = 14,15,16

PINKY_MPC_ANGLE = 0, 17, 18
PINKY_PIP_ANGLE = 17,18,19
PINKY_DIP_ANGLE = 18,19,20



In [3]:
refLoc = [[408, 589, 0], [364, 589, -473], [324, 564, -880], [309, 527, -1286], [308, 482, -1607], [328, 392, -654], [329, 385, -1229], [338, 450, -1429], [343, 494, -1493], [369, 375, -744], [369, 400, -1338], [372, 481, -1326], [376, 526, -1226], [409, 385, -912], [406, 424, -1443], [403, 494, -1282], [404, 530, -1075], [447, 411, -1149], [441, 441, -1450], [435, 494, -1360], [434, 524, -1214]]

In [4]:
refLoc[0]

[408, 589, 0]

In [5]:
import numpy as np
import math

def angle_2p_3d(a, b, c):

    v1 = np.array([ a[0] - b[0], a[1] - b[1], a[2] - b[2] ])
    v2 = np.array([ c[0] - b[0], c[1] - b[1], c[2] - b[2] ])

    v1mag = np.sqrt([ v1[0] * v1[0] + v1[1] * v1[1] + v1[2] * v1[2] ])
    v1norm = np.array([ v1[0] / v1mag, v1[1] / v1mag, v1[2] / v1mag ])

    v2mag = np.sqrt(v2[0] * v2[0] + v2[1] * v2[1] + v2[2] * v2[2])
    v2norm = np.array([ v2[0] / v2mag, v2[1] / v2mag, v2[2] / v2mag ])
    res = v1norm[0] * v2norm[0] + v1norm[1] * v2norm[1] + v1norm[2] * v2norm[2]
    angle_rad = np.arccos(res)

    return math.degrees(angle_rad)

In [10]:
p1 = refLoc[0]
p2 = refLoc[1]
p3 = refLoc[2]

angle = angle_2p_3d(p1, p2, p3)

In [17]:
import numpy as np

In [18]:
dial = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [21]:
str(dial[0])

'[1 2 3]'

In [46]:

    reshape = np.array([THUMB_CMC_ANGLE,THUMB_MPC_ANGLE,THUMB_IP_ANGLE,
                        INDEX_MCP_ANGLE,INDEX_PIP_ANGLE,INDEX_DIP_ANGLE,
                        MIDDLE_MPC_ANGLE,MIDDLE_PIP_ANGLE,MIDDLE_DIP_ANGLE,
                        RING_MPC_ANGLE,RING_PIP_ANGLE,RING_DIP_ANGLE,
                        PINKY_MPC_ANGLE,PINKY_PIP_ANGLE,PINKY_DIP_ANGLE
                        ]).reshape(5,3)
    reshape = reshape.astype(int)
    reshape = np.rot90(reshape)
    reshape = np.flipud(reshape)
    reshape

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [30]:
THUMB_CMC_ANGLE = 0
THUMB_MPC_ANGLE = 1
THUMB_IP_ANGLE = 2

INDEX_MCP_ANGLE = 3
INDEX_PIP_ANGLE = 4
INDEX_DIP_ANGLE = 5

MIDDLE_MPC_ANGLE = 6
MIDDLE_PIP_ANGLE = 7
MIDDLE_DIP_ANGLE = 8

RING_MPC_ANGLE = 9
RING_PIP_ANGLE = 10
RING_DIP_ANGLE = 11

PINKY_MPC_ANGLE = 12
PINKY_PIP_ANGLE = 13
PINKY_DIP_ANGLE = 14



array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [45]:
print(str(reshape[:][:]))

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
